apps/api/urls.py
from django.conf.urls import url

from apps.api.views import (
    APIOrderView, APIStrategyCreateView,
    strategy_set_value_view, strategy_delete_key_view, strategy_delete_view, APIAccountCreateView,
    start_strategy_view, down_strategy_view,
    close_orders_view, get_history_view,
    get_orders_view, sell_all_view)

app_name = 'api'

urlpatterns = [
    url(r'^orders/(?P<exchange_name>[\w.@+-]+)/$', APIOrderView.as_view(), name='api_order_list'),
    url(r'^strategy/create/$', APIStrategyCreateView.as_view(), name='api_strategy_create'),
    url(r'^account/create/$', APIAccountCreateView.as_view(), name='api_account_create'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/up/$', start_strategy_view,
        name='start_strategy_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/down/$', down_strategy_view,
        name='down_strategy_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/close_orders/$', close_orders_view,
        name='close_orders_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/sell_all/$', sell_all_view,
        name='sell_all_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/get_orders/$', get_orders_view,
        name='get_orders_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/get_history/$', get_history_view,
        name='get_history_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/delete/$', strategy_delete_view,
        name='strategy_delete_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/key/edit/$', strategy_set_value_view,
        name='strategy_set_value_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/key/delete/$', strategy_delete_key_view,
        name='strategy_delete_key_view')
]

apps/order/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.order import views

app_name = 'order'

urlpatterns = [
    url(
        regex=r'^(?P<exchange_name>[\w.@+-]+)/$',
        view=login_required(views.OrderView.as_view()),
        name='list'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='dashboard/index.html'), name='index'),

    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^accounts/login/$', LoginView.as_view(), name="login"),
    url(r'^accounts/logout/$', LogoutView.as_view(), name="logout"),

    url(r'^api/', include('apps.api.urls')),

    url(r'^accounts/', include('apps.profile_app.urls')),
    url(r'^orders/', include('apps.order.urls')),
    url(r'^strategy/', include('apps.strategy.urls')),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

apps/order/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models

from apps.order import constants


class Exchange(models.Model):
    name = models.CharField(max_length=255, choices=constants.EXCHANGES_CHOICES, unique=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.get_name_display()


class Order(models.Model):
    ORDER_TYPE_CHOICES = (
        (constants.ORDER_TYPE_BUY, constants.ORDER_TYPE_BUY.lower()),
        (constants.ORDER_TYPE_SELL, constants.ORDER_TYPE_SELL.lower()),
    )
    uuid = models.CharField(max_length=255, blank=True, null=True, help_text='Remote unique identifier')
    exchange = models.ForeignKey(Exchange, on_delete=models.CASCADE)
    account = models.ForeignKey('profile_app.Account', on_delete=models.CASCADE)

    type = models.CharField(max_length=5, choices=ORDER_TYPE_CHOICES)
    pair = models.CharField(max_length=20)

    quantity = models.DecimalField(blank=True, null=True, decimal_places=8, max_digits=12)
    commission = models.DecimalField(blank=True, null=True, decimal_places=8, max_digits=12)
    price = models.DecimalField(blank=True, null=True, decimal_places=8, max_digits=12)

    opened_at = models.DateTimeField(blank=True, null=True)
    closed_at = models.DateTimeField(blank=True, null=True)

    data = JSONField(default=dict, blank=True, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['uuid', ])
        ]


class Price(models.Model):
    exchange = models.ForeignKey(Exchange, on_delete=models.CASCADE)
    pair = models.CharField(max_length=10)
    ask = models.DecimalField(decimal_places=8, max_digits=12)
    bid = models.DecimalField(decimal_places=8, max_digits=12)
    timestamp = models.DateTimeField(blank=True, null=True)
    data = JSONField(blank=True, null=True)

    def __str__(self):
        return '{0}: {1}'.format(self.pair, self.ask)

    class Meta:
        unique_together = ('pair', 'exchange')

apps/order/forms.py
from django import forms
from django.forms import widgets


class OrderPeriodForm(forms.Form):
    min_date = forms.DateField(
        input_formats='dd.mm.yy',
        required=False,
        label='From:',
        widget=widgets.Input(
            attrs={'class': 'form-control date_range_filter date'}
        )
    )
    max_date = forms.DateField(
        input_formats='dd.mm.yy',
        required=False,
        label='To:',
        widget=widgets.Input(
            attrs={'class': 'form-control date_range_filter date'}
        )
    )
    pair = forms.ChoiceField(required=False)

    def clean(self):
        cleaned_data = super(OrderPeriodForm, self).clean()
        min_date = cleaned_data.get("min_date")
        max_date = cleaned_data.get("max_date")

        if min_date and max_date:
            if max_date < min_date:
                raise forms.ValidationError("End time cannot be earlier than start time!")
        return cleaned_data

apps/order/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from apps.order.forms import OrderPeriodForm
from apps.order.models import Exchange


class OrderView(LoginRequiredMixin, TemplateView):
    template_name = 'order/order_list.html'

    def dispatch(self, request, *args, **kwargs):
        get_object_or_404(Exchange, name=self.kwargs['exchange_name'])
        return super(OrderView, self).dispatch(request)

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data()
        context['form'] = OrderPeriodForm(self.request.GET)
        context['exchange_name'] = self.kwargs.get('exchange_name', 'none')
        return context

apps/order/templates/order/order_list.html
{% extends 'dashboard/base.html' %}
{% load bootstrap4 %}

{% load staticfiles %}

{% block css_imports %}
    <link rel="stylesheet" href="{% static 'datatables.net-dt/css/jquery.dataTables.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">#}
    <link rel="stylesheet" href="{% static 'jquery-ui-dist/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
{% endblock %}
{% block js_imports %}
    <script src="{% static 'datatables.net/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'jquery-ui-dist/jquery-ui.js' %}"></script>
    <script src="{% static 'order/js/utils.js' %}"></script>
{% endblock %}

{% block content %}
    <hr/>
    <p>Select search parameters:</p>
    <div class="grid">
        <div class="col-md-3">
            <form class="form">
            {% for field in form %}
                <div class="form-group {% if field.errors %}has-error{% endif %}" id="group_{{ field.name }}">
                    {% if not field.name == 'pair' %}
                        <i class="fa fa-calendar"></i>
                    {% else %}
                        <i class="fa fa-align-justify"></i>
                    {% endif %}
                    <label for="id_{{ field.name }}" class="control-label">{{ field.label }}</label>
                    <div class="input-group md-3">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
            </form>
        </div>
    </div>

    <hr/>
    <p>P&L:</p>
    <div class="col-md-4">
        <table class="table">
            <tbody>
                <tr>
                    <th>P&L Total:</th>
                    <td id="id-pnl-total"></td>
                </tr>
                <tr>
                    <th>P&L Realized:</th>
                    <td id="id-pnl-realized"></td>
                </tr>
                <tr>
                    <th>P&L Unrealized:</th>
                    <td id="id-pnl-unrealized"></td>
                </tr>
                <tr>
                    <th>Total commission:</th>
                    <td id="id-total-commission"></td>
                </tr>
                <tr>
                    <th>REVENUE:</th>
                    <td id="id-revenue"></td>
                </tr>
            </tbody>
        </table>
    </div>
    <h4>Orders:</h4>
    <table class="table table-responsive table-striped display nowrap" id="orders">
        <thead class="">
            <tr>
                <th>ID</th>
                <th>Exchange</th>
                <th>Type</th>
                <th>Pair</th>
                <th>Quantity</th>
                <th>Commission</th>
                <th>Price</th>
                <th>Closed</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
        <tfoot>
            <tr>
                <th>ID</th>
                <th>Exchange</th>
                <th>Type</th>
                <th>Pair</th>
                <th>Quantity</th>
                <th>Commission</th>
                <th>Price</th>
                <th>Closed</th>
            </tr>
        </tfoot>
    </table>
    <hr/>
{% endblock %}

{% block scripts %}
    <script type="application/javascript">
    $(document).ready( function () {
        var $form = $('.form');
        $form.on('submit', function (e) {
            e.preventDefault();
            var url = table.ajax.url();
            var parameters = $(this).serializeArray();
            for (var i in parameters) {
                url = updateURLParameter(url, parameters[i]['name'], parameters[i]['value'])
            }
            table.ajax.url(url).load();
            table.draw();
        });

        function init_pairs(pairs){
          var $self = $('#id_pair');
          var $option=$("<option>All</option>");
          $self.empty();
          $self.append($option);
          $.each(pairs, function(index, pair) {
            $option = $("<option></option>")
              .attr("value", pair)
              .text(pair);
            $self.append($option);
          });
        }

        $("#id_min_date").datepicker({
            onSelect: function (selected) {
                $("#id_max_date").datepicker("option","minDate", selected);
                $form.submit()
            },
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd.mm.yy'
        });

        $("#id_max_date").datepicker({
            onSelect: function (selected) {
                $("#id_min_date").datepicker("option","maxDate", selected);
                $form.submit()
            },
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd.mm.yy'
        });

        $('#id_pair').change(function () {
            $form.submit();
        });
        // DataTable
        var table = $('#orders').DataTable({
            "serverSide": true,
            "processing": true,
            "ajax": {
                url:"{% url 'api:api_order_list' exchange_name=exchange_name %}?format=datatables",
                dataSrc: function(json) {
                    var _pairs = json.pairs;
                    if (typeof _pairs !== 'undefined' && _pairs.length === 1){
                        $('#id-pnl-total').html(json.pnl_total);
                        $('#id-pnl-realized').html(json.pnl_realized);
                        $('#id-pnl-unrealized').html(json.pnl_unrealized);
                        $('#id-total-commission').html(json.total_commission);
                        $('#id-revenue').html(json.revenue);
                        init_pairs(_pairs);
                        $('#id_pair').val(_pairs);
                    }
                    if (typeof  _pairs !== 'undefined' && _pairs.length > 1 || _pairs.length === 0) {
                        $('#id-pnl-total').html(0);
                        $('#id-pnl-realized').html(0);
                        $('#id-pnl-unrealized').html(0);
                        $('#id-total-commission').html(0);
                        $('#id-revenue').html(0);
                        init_pairs(_pairs);
                    }
                    return json.data;
                }
            },
            "columns": [
                {"data": "id", "searchable": true},
                {"data": "exchange", "searchable": true, "name": "exchange.name"},
                {"data": "type", "searchable": true},
                {"data": "pair", "searchable": true},
                {"data": "quantity", "searchable": true},
                {"data": "commission", "searchable": true},
                {"data": "price", "searchable": true},
                {"data": "closed_at", "searchable": true},
            ]
        });

    } );
    </script>
    <style>
        table.dataTable tbody th, table.dataTable tbody td {
            padding: 8px 75px; /* e.g. change 8x to 4px here */
        }
    </style>
{% endblock %}