apps/api/urls.py
from django.conf.urls import url

from apps.api.views import (
    APIOrderView, APIStrategyCreateView,
    strategy_set_value_view, strategy_delete_key_view, strategy_delete_view, APIAccountCreateView,
    start_strategy_view, down_strategy_view,
    close_orders_view, get_history_view,
    get_orders_view, sell_all_view)

app_name = 'api'

urlpatterns = [
    url(r'^orders/(?P<exchange_name>[\w.@+-]+)/$', APIOrderView.as_view(), name='api_order_list'),
    url(r'^strategy/create/$', APIStrategyCreateView.as_view(), name='api_strategy_create'),
    url(r'^account/create/$', APIAccountCreateView.as_view(), name='api_account_create'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/up/$', start_strategy_view,
        name='start_strategy_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/down/$', down_strategy_view,
        name='down_strategy_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/close_orders/$', close_orders_view,
        name='close_orders_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/sell_all/$', sell_all_view,
        name='sell_all_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/get_orders/$', get_orders_view,
        name='get_orders_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/get_history/$', get_history_view,
        name='get_history_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/delete/$', strategy_delete_view,
        name='strategy_delete_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/key/edit/$', strategy_set_value_view,
        name='strategy_set_value_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/key/delete/$', strategy_delete_key_view,
        name='strategy_delete_key_view')
]

apps/strategy/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.strategy.views import StrategyView, StrategyDetailView

app_name = 'strategy'

urlpatterns = [
    url(regex=r'^$', view=login_required(StrategyView.as_view()), name='list'),
    url(regex=r'^(?P<pk>[\d+])/$', view=login_required(StrategyDetailView.as_view()), name='detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='dashboard/index.html'), name='index'),

    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^accounts/login/$', LoginView.as_view(), name="login"),
    url(r'^accounts/logout/$', LogoutView.as_view(), name="logout"),

    url(r'^api/', include('apps.api.urls')),

    url(r'^accounts/', include('apps.profile_app.urls')),
    url(r'^orders/', include('apps.order.urls')),
    url(r'^strategy/', include('apps.strategy.urls')),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

apps/strategy/models.py
import os

import docker
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
import uuid

from apps.strategy import gbot, constants

docker_client = docker.from_env()


class Strategy(models.Model):
    class Meta:
        verbose_name = 'Strategy'
        verbose_name_plural = 'Strategies'

    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    data = JSONField(blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    port = models.PositiveIntegerField(validators=[MinValueValidator(7000), MaxValueValidator(7500)], unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.pk}. {self.user}'

    def set_value(self, key, value):
        self.data[key] = value
        self.save(update_fields=['data', 'updated_at'])

    def delete_key(self, key):
        self.data.pop(key)
        self.save(update_fields=['data', 'updated_at'])

    def up_container(self):
        env_data = self.data
        env_data.update(constants.STRATEGY_WEB_AUT_ENV)
        env_data.update({"PORT": f'{self.port}'})

        try:
            paths = [
                "{0}:{1}".format(
                    os.path.join(settings.HOST_PWD, 'bots-logs', str(self.uuid)),
                    env_data['LOG_PATH']),
            ]
            container = docker_client.containers.run(
                name=self.uuid,
                image='gbot',
                # network='mitra_mitra',
                environment=env_data,
                ports={f'{self.port}/tcp': self.port},
                detach=True,
                links=[('mitra_web', 'mitra_web'), ],
                volumes=paths,
            )
        except (docker.errors.APIError) as e:
            return e
        return container

    def get_container(self):
        try:
            container = docker_client.containers.get(str(self.uuid))
        except (docker.errors.NotFound, docker.errors.APIError) as e:
            return e
        return container

    def container_log(self):
        container = self.get_container()
        return container.logs()

    def down_container(self):
        container = self.get_container()
        container.stop()
        container.remove()
        return True

    def close_all_orders(self):
        client = gbot.Client(host=f'http://{str(self.uuid)}', port=f'{self.port}')
        response = client.close_orders()
        return response

    def get_orders(self):
        client = gbot.Client(host=f'http://{str(self.uuid)}', port=f'{self.port}')
        response = client.get_orders()
        return response

    def get_history(self):
        client = gbot.Client(host=f'http://{str(self.uuid)}', port=f'{self.port}')
        response = client.get_history()
        return response

    def sell_all(self):
        client = gbot.Client(host=f'http://{str(self.uuid)}', port=f'{self.port}')
        response = client.sell_all()
        return response

apps/strategy/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from apps.strategy.constants import CREATE_STRATEGY_DEFAULTS
from apps.strategy.models import Strategy


class StrategyView(LoginRequiredMixin, generic.ListView):
    model = Strategy
    template_name = 'strategy/strategy_list.html'
    ordering = '-updated_at'

    def get_queryset(self):
        qs = super(StrategyView, self).get_queryset()
        return qs.filter(user=self.request.user, is_deleted=False)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(StrategyView, self).get_context_data()
        context['create_strategy_defaults'] = CREATE_STRATEGY_DEFAULTS
        return context


class StrategyDetailView(generic.DetailView):
    model = Strategy
    template_name = 'strategy/strategy_detail.html'

apps/strategy/templates/strategy/strategy_detail.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}

{% block css_imports %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'datatables.net-dt/css/jquery.dataTables.css' %}">
    <link rel="stylesheet" href="{% static 'jquery-ui-dist/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
{% endblock %}

{% block js_imports %}
    {{ block.super }}
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <table class="table">
                <tbody>
                {% for key, value in object.data.items %}
                    <tr>
                        <td><input class="form-control" type="text" value="{{ key }}" readonly></td>
                        <td><input class="form-control" type="text" value="{{ value }}" readonly></td>
                        <td>
                            <a href="#"
                               data-toggle="modal"
                               data-key="{{ key }}"
                               data-value="{{ value }}"
                               data-target="#modalEdit"><i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            <div id="deleteKey">
                                <a href="{% url 'api:strategy_delete_key_view' object.uuid %}" data-key="{{ key }}"><i class="fa fa-times" aria-hidden="true"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                    <tr>
                        <form action="{% url 'api:strategy_set_value_view' object.uuid %}" id="newKey">
                            {% csrf_token %}
                            <td><input class="form-control" type="text" name="key"></td>
                            <td><input class="form-control" type="text" name="value"></td>
                            <td><input type="submit" class="btn btn-success btn-block" value="Add"></td>
                        </form>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-1">
        </div>
        <div class="col-md-2">
            <br>
            <form action="{% url 'api:start_strategy_view' object.uuid %}" method="post" class="action-form">
                {% csrf_token %}
                <input class="btn btn-secondary btn-block" type="submit" value="up">
            </form>
            <p></p>
            <form action="{% url 'api:close_orders_view' object.uuid %}" method="post" class="action-form">
                {% csrf_token %}
                <input class="btn btn-secondary btn-block" type="submit" value="close orders">
            </form>
            <p></p>
            <form action="{% url 'api:get_orders_view' object.uuid %}" method="post" class="">
                {% csrf_token %}
                <input class="btn btn-danger btn-block" type="submit" value="get orders" data-toggle="modal" data-target="#modalAction">
            </form>
            <p></p>
            <form action="{% url 'api:sell_all_view' object.uuid %}" method="post" class="">
                {% csrf_token %}
                <input class="btn btn-danger btn-block" type="submit" value="sell all" data-toggle="modal">
            </form>
            <p></p>
            <form action="{% url 'api:get_history_view' object.uuid %}" method="post" class="action-form">
                {% csrf_token %}
                <input class="btn btn-danger btn-block" type="submit" value="get history">
            </form>
            <p></p>
            <form action="{% url 'api:down_strategy_view' object.uuid %}" method="post" class="action-form">
                {% csrf_token %}
                <input class="btn btn-secondary btn-block" type="submit" value="down">
            </form>
        </div>
    </div>

    <div class="modal" id="modalEdit" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Edit</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- body -->
                <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{% url 'api:strategy_set_value_view' object.uuid %}" method="post" class="form-inline" id="strategyEdit">
                            {% csrf_token %}
                            <div class="col-md-3">
                                <span class="input-group-addon" id="key"></span>
                            </div>
                            <div class="col-md-5">
                                <input class="form-control" type="text" value="" name="value" id="value">
                            </div>
                            <div class="col-md-4">
                                <input class="form-control btn btn-sm btn-success" type="submit" value="Change">
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="modalAction" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- body -->
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript">
        $(document).ready(function () {
            $(document).on('click', "#deleteKey", function (event) {
                event.preventDefault();
                var url = $(this).children("a").attr('href');
                var key = $(this).children("a").attr('data-key');
                var csrf = $("{% csrf_token %}");
                $.ajax({
                   type: "POST",
                   url: url,
                   data: csrf.serialize() + '&' + "key="+key,
                   success: function(data)
                   {
                       location.reload();
                   }
                });

            });
        });
        function render_kv_form(key, value) {
            $('span#key').html(key);
            $('input#value').attr('value', value);
        }
        $('#newKey').on('submit', function (event) {
            event.preventDefault();
            var form = $(this);
            $.ajax({
                type: "POST",
                url: form.attr('action'),
                data: form.serialize(),
                success: function(data)
                {
                    location.reload();
                }
            });
        });
        $('#strategyEdit').on('submit', function (event) {
            event.preventDefault();
            var form = $(this);
            var key = $('#key').text();
            var data = form.serialize();
            var url = form.attr('action');
            $.ajax({
               type: "POST",
               url: url,
               data: data + '&key=' + key,
               success: function(data)
               {
                   $('#modalEdit').modal('hide');
               }
             });
        });
        $('.action-form').on('submit', function (event) {
            event.preventDefault();
            var form = $(this);
            var url = form.attr('action');
            $.ajax({
                type: "POST",
                url: url,
                data: form.serialize(),
                success: function(data)
               {
                   $('#success-alert').show()
               }
            })

        });
        $('#modalEdit').on('show.bs.modal', function (event) {
            var $link = $(event.relatedTarget);
            var key = $link.attr('data-key');
            var value = $link.attr('data-value');
            render_kv_form(key, value);
        });
        $('#modalEdit').on('hide.bs.modal', function (event) {
            location.reload();
        });

        $('#modalAction').on('show.bs.modal', function (event) {
        });

        $('#modalAction').on('hide.bs.modal', function (event) {
            location.reload();
        });
    </script>
{% endblock %}

apps/strategy/templates/strategy/strategy_list.html
{% extends 'dashboard/base.html' %}
{% block content %}
    <h4>Strategies: </h4>
    <p><button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#modalCreate">Create new</button></p>

    <div class="list-group">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Exchange</th>
                <th>Pair</th>
                <th>Created at</th>
                <th>Updated at</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for strategy in strategy_list %}
                <tr>
                    <td onclick="window.location='{% url 'strategy:detail' strategy.pk %}'">{{ strategy.data.EXCHANGE }}</td>
                    <td onclick="window.location='{% url 'strategy:detail' strategy.pk %}'">{{ strategy.data.NAME_COIN }} - {{ strategy.data.NAME_COIN_TWO }}</td>
                    <td onclick="window.location='{% url 'strategy:detail' strategy.pk %}'">{{ strategy.created_at }}</td>
                    <td onclick="window.location='{% url 'strategy:detail' strategy.pk %}'">{{ strategy.updated_at }}</td>
                    <td>
                        <form action="{% url 'api:strategy_delete_view' strategy.uuid %}" method="post" id="deleteStrategy">
                            {% csrf_token %}
                            <input class="btn btn-small btn-danger" type="submit" value="delete">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- Create strategy Modal -->
    <div class="modal" id="modalCreate" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Create new strategy</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- body -->
                <div class="modal-body">
                    <form action="{% url 'api:api_strategy_create' %}" class="form" id="createStrategyForm" method="post">
                        <div class="col-sm-12 validation-errors"></div>
                        {% csrf_token %}
                        {% for key, value in create_strategy_defaults.items %}
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <input type="text" class="form-control" aria-describedby="basic-addon2" name="key" value="{{ key }}" readonly>
                                </div>
                                <input type="text" class="form-control" aria-describedby="basic-addon2" name="value" required>
                            </div>
                            <br/>
                        {% endfor %}
                        <p></p>
                        <input type="submit" class="btn btn-success" value="Save">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript">
        function activateRow (row) {
            row.find('input').removeAttr('readonly');
            row.find('.edit-row').toggleClass('edit-row save-row')
        }

        function saveRow (row) {
            $form = row.parents('form');
            $form.submit();
        }

        function createStrategy(form) {
            var $form = form;
            var action = $form.attr('action');
            var data = $form.serialize();
            $.post(action, data)
                .done(function (data) {
                    if (data.success === false) {
                        data.errors.data.forEach(function (item) {
                            var $validation_error = $('<p><small class="text-danger">'+item+'<small></p>');
                            $('.validation-errors').append($validation_error)
                        })
                    }
                    else {
                        $('#modalCreate').modal('hide');
                    }
                })
        }
        function deleteStrategy(form) {
            var $form = form;
            console.log($form);
            var action = $form.attr('action');
            var data = $form.serialize();
            $.post(action, data)
                .done(function (data) {
                    location.reload();
                })
        }

        $(document).on("click", ".save-row", function(event){
            saveRow($(this).parents('.input-group'))
        });

        $(document).on("click", ".edit-row", function(event){
            activateRow($(this).parents('.input-group'))
        });

        $(document).on('submit', '#createStrategyForm', function (event) {
            event.preventDefault();
            $('.validation-errors').html('');
            createStrategy($(this))
        });
        $(document).on('submit', '#deleteStrategy', function (event) {
            event.preventDefault();

            deleteStrategy($(this))
        });

        $('#modalCreate').on('show.bs.modal', function (event) {
        });

        $('#modalCreate').on('hide.bs.modal', function (event) {
            location.reload();
        });

    </script>

{% endblock %}