apps/api/urls.py
from django.conf.urls import url

from apps.api.views import (
    APIOrderView, APIStrategyCreateView,
    strategy_set_value_view, strategy_delete_key_view, strategy_delete_view, APIAccountCreateView,
    start_strategy_view, down_strategy_view,
    close_orders_view, get_history_view,
    get_orders_view, sell_all_view)

app_name = 'api'

urlpatterns = [
    url(r'^orders/(?P<exchange_name>[\w.@+-]+)/$', APIOrderView.as_view(), name='api_order_list'),
    url(r'^strategy/create/$', APIStrategyCreateView.as_view(), name='api_strategy_create'),
    url(r'^account/create/$', APIAccountCreateView.as_view(), name='api_account_create'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/up/$', start_strategy_view,
        name='start_strategy_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/down/$', down_strategy_view,
        name='down_strategy_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/close_orders/$', close_orders_view,
        name='close_orders_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/sell_all/$', sell_all_view,
        name='sell_all_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/get_orders/$', get_orders_view,
        name='get_orders_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/manage/get_history/$', get_history_view,
        name='get_history_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/delete/$', strategy_delete_view,
        name='strategy_delete_view'),

    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/key/edit/$', strategy_set_value_view,
        name='strategy_set_value_view'),
    url(r'^strategy/(?P<strategy_uuid>[\w.@+-]+)/key/delete/$', strategy_delete_key_view,
        name='strategy_delete_key_view')
]

apps/profile_app/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.profile_app import views

app_name = 'profile_app'

urlpatterns = [
    url(
        regex=r'$',
        view=login_required(views.AccountsView.as_view()),
        name='accounts'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='dashboard/index.html'), name='index'),

    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^accounts/login/$', LoginView.as_view(), name="login"),
    url(r'^accounts/logout/$', LogoutView.as_view(), name="logout"),

    url(r'^api/', include('apps.api.urls')),

    url(r'^accounts/', include('apps.profile_app.urls')),
    url(r'^orders/', include('apps.order.urls')),
    url(r'^strategy/', include('apps.strategy.urls')),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

apps/profile_app/models.py
from django.contrib.auth.models import User
from django.db import models

from apps.order.models import Exchange


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exchange = models.ForeignKey(Exchange, on_delete=models.CASCADE)
    email = models.EmailField(blank=True, null=True)
    username = models.CharField(max_length=255, blank=True)
    password = models.CharField(max_length=255, blank=True)
    api_key = models.CharField(max_length=255, blank=True, null=True)
    api_secret = models.CharField(max_length=255, blank=True, null=True)
    is_active = models.BooleanField(default=True, help_text='Is active account on exchange')

apps/profile_app/forms.py
from django import forms
from django.forms import widgets

from apps.profile_app.models import Account


class AccountCreateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('exchange', 'api_key', 'api_secret')

        base_widget = widgets.Input(attrs={'class': 'form-control'})
        widgets = {
            'exchange': base_widget,
            'api_key': base_widget,
            'api_secret': base_widget,

        }

apps/profile_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from apps.profile_app.constants import CREATE_ACCOUNT_DEFAULTS
from apps.profile_app.forms import AccountCreateForm
from apps.profile_app.models import Account


class AccountsView(LoginRequiredMixin, generic.ListView):
    template_name = 'profile_app/account_list.html'
    model = Account

    def get_queryset(self):
        qs = super(AccountsView, self).get_queryset()
        return qs.filter(user=self.request.user, is_active=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['create_account_defaults'] = CREATE_ACCOUNT_DEFAULTS
        context['create_account_form'] = AccountCreateForm
        return context

apps/profile_app/templates/profile_app/account_list.html
{% extends 'dashboard/base.html' %}
{% load bootstrap4 %}
{% block content %}
<h4>Exchange accounts: </h4>
<p><button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#modalCreate">Add</button></p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Exchange</th>
            <th>Key</th>
        </tr>
    </thead>
    <tbody>
    {% for account in account_list %}
        <tr>
            <td>{{ account.exchange }}</td>
            <td>{{ account.api_key }}</td>
        </tr>
    {% endfor %}
    </tbody>

</table>

<!-- Create account Modal -->
<div class="modal" id="modalCreate" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add account from Exchange</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- body -->
            <div class="modal-body">
                <form action="{% url 'api:api_account_create' %}" class="form" id="createAccountForm" method="post">
                    <div class="col-sm-12 validation-errors"></div>
                    {% csrf_token %}
                    {% for field in create_account_form %}
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <input type="text" class="form-control" aria-describedby="basic-addon2" value="{{ field.label }}" readonly>
                            </div>
                            {{ field }}
                        </div>
                    <br>
                    {% endfor %}
                    <input type="submit" class="btn btn-success" value="Save">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript">
        function createAccount(form) {
            var $form = form;
            var action = $form.attr('action');
            var data = $form.serialize();

            $.post(action, data)
                .done(function (data) {
                    if (data.success === false) {
                        for (var error in data.errors) {
                            var $validation_error = $('<p><small class="text-danger">'+data.errors[error]+'<small></p>');
                            $('.validation-errors').append($validation_error)
                        }
                    }
                    else {
                        $('#modalCreate').modal('hide');
                    }
                })
            }
        $(document).on('submit', '#createAccountForm', function (event) {
            event.preventDefault();
            $('.validation-errors').html('');
            createAccount($(this))
        });

        $('#modalCreate').on('show.bs.modal', function (event) {
        });

        $('#modalCreate').on('hide.bs.modal', function (event) {
            location.reload();
        });

    </script>
{% endblock %}