apps/order/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.order import views

app_name = 'order'

urlpatterns = [
    url(
        regex=r'^(?P<exchange_name>[\w.@+-]+)/$',
        view=login_required(views.OrderView.as_view()),
        name='list'
    ),
]

apps/profile_app/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.profile_app import views

app_name = 'profile_app'

urlpatterns = [
    url(
        regex=r'$',
        view=login_required(views.AccountsView.as_view()),
        name='accounts'
    ),
]

apps/strategy/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.strategy.views import StrategyView, StrategyDetailView

app_name = 'strategy'

urlpatterns = [
    url(regex=r'^$', view=login_required(StrategyView.as_view()), name='list'),
    url(regex=r'^(?P<pk>[\d+])/$', view=login_required(StrategyDetailView.as_view()), name='detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='dashboard/index.html'), name='index'),

    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^accounts/login/$', LoginView.as_view(), name="login"),
    url(r'^accounts/logout/$', LogoutView.as_view(), name="logout"),

    url(r'^api/', include('apps.api.urls')),

    url(r'^accounts/', include('apps.profile_app.urls')),
    url(r'^orders/', include('apps.order.urls')),
    url(r'^strategy/', include('apps.strategy.urls')),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

apps/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
{% load bootstrap4 staticfiles project_info %}
{% exchanges_online as exchanges_online %}
<html lang="en">
<head>
    <title>{% block title %}{% project_name %}{% endblock %}</title>
    <meta charset="UTF-8">
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.css' %}">
    {% bootstrap_javascript jquery='full' %}
    {% block css_imports %}
        <link rel="stylesheet" href="{% static 'jquery-ui-dist/jquery-ui.css' %}">
    {% endblock %}
    {% block js_imports %}
        <script type="application/javascript" src="{% static 'jquery-ui-dist/jquery-ui.js' %}"></script>
    {% endblock %}
    <style>
    {% block css %}{% endblock %}
    </style>
</head>
<body>
{% bootstrap_messages %}
<div class="container-fluid">
    {% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a href="/"><img src="{% static 'img/logo.png' %}" width="50" height="50"></a>
        {% if request.user.is_authenticated %}
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                {% for exchange in exchanges_online %}
                    <li class="nav-item active">
                        <a class="nav-link"
                           href="{% url 'order:list' exchange_name=exchange.name %}"
                           role="button" aria-haspopup="true"
                           aria-expanded="false"
                        >{{ exchange.name|title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
        <div class="mx-auto order-0"></div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'strategy:list' %}">Strategy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile_app:accounts' %}">Accounts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% endblock %}
    <div class="content">
        <div class="alert alert-success" id="success-alert" style="display: none">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <strong>Success! </strong>
            Saved
        </div>
        {% block content %}{% endblock %}
    </div>
    {% block scripts %}{% endblock %}
</div>
</body>

</html>

apps/dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block css_imports %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.css' %}">
{% endblock %}

{% block content %}

{% endblock %}